services:
    php5:
        build: .
        restart: unless-stopped
        stop_grace_period: 10s
        ports:
            - "8080:80"
        extra_hosts:
          - host.docker.internal:host-gateway
        volumes:
          - ".:/var/www/html"

